module:
  aa_content: 0
  aa_core: 0
  aa_report: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  auto_entitylabel: 0
  automated_cron: 0
  backup_migrate: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  config: 0
  contextual: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  environment_indicator: 0
  environment_indicator_ui: 0
  feeds: 0
  field: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  geolocation: 0
  google_analytics: 0
  help: 0
  history: 0
  image: 0
  language: 0
  link: 0
  locale: 0
  mask: 0
  masquerade: 0
  menu_ui: 0
  migrate: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  node: 0
  noreqnewpass: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  regex_field_validation: 0
  rest: 0
  search: 0
  serialization: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  username_validation: 0
  views_custom_regex: 0
  views_data_export: 0
  views_field_formatter: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  olivero: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: es
